### ISSUE TITLE
Missing search does not run

### ISSUE THREAD

**Issue by sentrywasbored** [primetime43/GAPS-2#12]
does not run, outputs error in console stating global_recommendations is not defined

```
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /recommended HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/page/recommended.min.js HTTP/1.1" 404 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/libraries/dataTables.bootstrap4.min.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/input.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/datatables.min.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/jquery-3.4.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/libraries/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/libraries/datatables.min.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/sockjs-1.4.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/stomp-2.3.3.min.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/bootstrap.bundle.min.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/handlebars-v4.7.6.min.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/arrow-clockwise.svg HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/info-circle.svg HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/list-ul.svg HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/final-gaps.svg HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/collection-fill.svg HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/gear.svg HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/mind_the_gap.png HTTP/1.1" 200 -
[2024-09-15 20:57:04,367] ERROR in app: Exception on /get_recommendated_movies [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2190, in wsgi_app
  File "flask\app.py", line 1486, in full_dispatch_request
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "GAPS 2.py", line 314, in get_recommendated_movies
NameError: name 'global_recommendations' is not defined
127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /get_recommendated_movies HTTP/1.1" 500 -
```

**Comment by primetime43** [comment]
> does not run, outputs error in console stating global_recommendations is not defined
> 
> 
> 
> ```
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /recommended HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/page/recommended.min.js HTTP/1.1" 404 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/libraries/dataTables.bootstrap4.min.css HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/input.css HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/datatables.min.js HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/jquery-3.4.1.min.js HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/libraries/bootstrap.min.css HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/css/libraries/datatables.min.css HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/sockjs-1.4.0.min.js HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/stomp-2.3.3.min.js HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/bootstrap.bundle.min.js HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/js/libraries/handlebars-v4.7.6.min.js HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/arrow-clockwise.svg HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/info-circle.svg HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/list-ul.svg HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/final-gaps.svg HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/collection-fill.svg HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/gear.svg HTTP/1.1" 200 -
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /static/images/mind_the_gap.png HTTP/1.1" 200 -
> 
> [2024-09-15 20:57:04,367] ERROR in app: Exception on /get_recommendated_movies [GET]
> 
> Traceback (most recent call last):
> 
>   File "flask\app.py", line 2190, in wsgi_app
> 
>   File "flask\app.py", line 1486, in full_dispatch_request
> 
>   File "flask\app.py", line 1484, in full_dispatch_request
> 
>   File "flask\app.py", line 1469, in dispatch_request
> 
>   File "GAPS 2.py", line 314, in get_recommendated_movies
> 
> NameError: name 'global_recommendations' is not defined
> 
> 127.0.0.1 - - [15/Sep/2024 20:57:04] "GET /get_recommendated_movies HTTP/1.1" 500 -
> 
> ```

Okay, it's been awhile since I've worked on this project due to time & other projects I've been working on. I hope to eventually get back to this one to do improvements/a rewrite.
