### ISSUE TITLE
Config doesn't appear to save

### ISSUE THREAD

**Issue by Trekgater** [primetime43/GAPS-2#6]
After entering the API key and setting Plex server 

The log shows 
192.168.0.10 - - [02/Oct/2023 18:12:59] "POST /saveTmdbKey HTTP/1.1" 200 -
when Saving the TMDB Key

Saving the plex server comes up with 
192.168.0.10 - - [02/Oct/2023 18:14:29] "POST /save_plex_data HTTP/1.1" 200 -
192.168.0.10 - - [02/Oct/2023 18:14:29] "GET /get_active_server HTTP/1.1" 200 -

After going to libraries, movies get listed from the libray I pick, when going to Missing 
it just shows mind tha gap and this shows in the log

[2023-10-02 18:15:14,826] ERROR in app: Exception on /get_recommendated_movies [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2190, in wsgi_app
  File "flask\app.py", line 1486, in full_dispatch_request
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "GAPS 2.py", line 314, in get_recommendated_movies
NameError: name 'global_recommendations' is not defined

After closing GAPS2.exe and restarting, clicking libraries shows a broken bridge picture with The gap is only getting bigger

Going into settings and while the Active TMDB shows clicking test shows failed - log shows in red text
192.168.0.10 - - [02/Oct/2023 18:19:57] "POST /testTmdbKey HTTP/1.1" 401 -

Clicking on Plex tab shows nothing
clicking on Fetch servers shows
[2023-10-02 18:20:57,481] ERROR in app: Exception on /fetch_servers [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2190, in wsgi_app
  File "flask\app.py", line 1486, in full_dispatch_request
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "GAPS 2.py", line 83, in fetch_servers
AttributeError: 'NoneType' object has no attribute 'checkLogin'
192.168.0.10 - - [02/Oct/2023 18:20:57] "POST /fetch_servers HTTP/1.1" 500 -

**Comment by primetime43** [comment]
Okay thanks. I'll look into it.

**Comment by primetime43** [comment]
Fixed in v2.0.0
